### ISSUE TITLE
Schedule an image posting with content warning every 6 hours

### ISSUE THREAD

**Issue by spinning-fantasies** [spinning-fantasies/wikihow_museum_bot#5]
Today we learnt how iterate on a directory using ``iterdir``.

Using ``with open(text, 'r', encoding='utf-8') as file:`` we can read the content of a given file.

Using ChatGPT we managed to refactor ``scheduled_status_post.py`` so we can schedule our posts from here.

Now I'd like to know how to combine these two features so we can post an image along with it's text description 🤔 

@sanders41 Do you have any idea how to achieve this ? Thanks for your help !

**Comment by sanders41** [comment]
The general direction I think would take here is while looping through the files in `ocr.py` you could make a call to `schedule_posts`, refactoring `schedule_posts` to take the needed information as parameters. This would let you only loop through the files one time.

Let me know if this makes since and/or if you have any questions about the rafactoring.

**Comment by spinning-fantasies** [comment]
I updated the ``ocr.py`` script and posting is OK, except when I try to schedule post, I have this error that I don't understand :

```
Traceback (most recent call last):
  File "/Users/mathieu/Code/Python/wikihow_museum_bot/ocr.py", line 84, in <module>
    status_response = requests.post(f'{api_base_url}/api/v1/statuses', headers=status_headers, data=json.dumps(status_payload))
                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

**Comment by sanders41** [comment]
Converting the `scheduled_time` to an iso string should fix this error.

```py
    status_payload = {
        'status': cw_status + "#WikihowMuseum",
        'media_ids': [media_id],
        'sensitive': True,
        'spoiler_text': status,
        'visibility': 'public',  # Set the visibility as needed
        'description': description,
        'scheduled_at': scheduled_time.isoformat()
    }
```

**Comment by spinning-fantasies** [comment]
Thanks ! It seems to work but I think I'm doing a mistake when setting  ``the schedulde_time`` :

```
#Set schedule
    interval_hours = 6  # Interval between posts
    current_time = datetime.now(timezone.utc)
    scheduled_time = current_time + timedelta(hours= 1 * interval_hours)
```

What I want is that an image is posted every 6 hours, and I don't find any answer on how to do it on the documentation at https://docs.python.org/3/library/datetime.html

The interval in between scheduled_at values is not good :

<img width="484" alt="Capture d’écran 2023-08-26 à 10 55 50" src="https://github.com/spinning-fantasies/wikihow_museum_bot/assets/133113709/c5bc0106-8522-4d83-aa2e-b8dfa0bb2fc8">

**Comment by spinning-fantasies** [comment]
I modified my loop : ``for x in range(0, len(file_list)):`` which let me access to the ``x`` variable and increase my ``    scheduled_time = current_time + interval * x`` and enable me to schedule a post every 6 hour.

Thanks again for your help !
